"""Add segments, personal records, and injury risk tables

Revision ID: f5fe23df9eda
Revises: 66a13e4c23a9
Create Date: 2025-12-06 06:49:20.004430
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'f5fe23df9eda'
down_revision = '66a13e4c23a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before creating them (idempotent migration)
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'app_state' not in existing_tables:
        op.create_table('app_state',
            sa.Column('key', sa.String(), nullable=False),
            sa.Column('value', sa.JSON(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('key')
        )
    
    if 'segments' not in existing_tables:
        op.create_table('segments',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('strava_segment_id', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('activity_type', sa.String(), nullable=False),
            sa.Column('distance_meters', sa.Float(), nullable=False),
            sa.Column('city', sa.String(), nullable=True),
            sa.Column('state', sa.String(), nullable=True),
            sa.Column('country', sa.String(), nullable=True),
            sa.Column('average_grade', sa.Float(), nullable=True),
            sa.Column('maximum_grade', sa.Float(), nullable=True),
            sa.Column('elevation_high', sa.Float(), nullable=True),
            sa.Column('elevation_low', sa.Float(), nullable=True),
            sa.Column('total_elevation_gain', sa.Float(), nullable=True),
            sa.Column('athlete_count', sa.Integer(), nullable=True),
            sa.Column('effort_count', sa.Integer(), nullable=True),
            sa.Column('star_count', sa.Integer(), nullable=True),
            sa.Column('raw_data', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_segments_strava_segment_id'), 'segments', ['strava_segment_id'], unique=True)
    
    if 'injury_risks' not in existing_tables:
        op.create_table('injury_risks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('risk_level', sa.String(), nullable=False),
            sa.Column('risk_type', sa.String(), nullable=False),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('recommendation', sa.Text(), nullable=False),
            sa.Column('trigger_metrics', sa.JSON(), nullable=True),
            sa.Column('detected_date', sa.Date(), nullable=False),
            sa.Column('acknowledged', sa.Boolean(), nullable=True),
            sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
            sa.Column('resolved', sa.Boolean(), nullable=True),
            sa.Column('resolved_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_injury_risks_detected_date'), 'injury_risks', ['detected_date'], unique=False)
        op.create_index(op.f('ix_injury_risks_user_id'), 'injury_risks', ['user_id'], unique=False)
    
    if 'personal_records' not in existing_tables:
        op.create_table('personal_records',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('activity_id', sa.Integer(), nullable=True),
            sa.Column('sport_type', sa.String(), nullable=False),
            sa.Column('distance_category', sa.String(), nullable=False),
            sa.Column('distance_meters', sa.Float(), nullable=False),
            sa.Column('time_seconds', sa.Integer(), nullable=False),
            sa.Column('pace_per_km', sa.Float(), nullable=True),
            sa.Column('speed_kmh', sa.Float(), nullable=True),
            sa.Column('average_heartrate', sa.Float(), nullable=True),
            sa.Column('average_watts', sa.Float(), nullable=True),
            sa.Column('elevation_gain', sa.Float(), nullable=True),
            sa.Column('achieved_date', sa.DateTime(), nullable=False),
            sa.Column('activity_name', sa.String(), nullable=True),
            sa.Column('is_current_pr', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('superseded_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_personal_records_achieved_date'), 'personal_records', ['achieved_date'], unique=False)
        op.create_index(op.f('ix_personal_records_activity_id'), 'personal_records', ['activity_id'], unique=False)
        op.create_index(op.f('ix_personal_records_distance_category'), 'personal_records', ['distance_category'], unique=False)
        op.create_index(op.f('ix_personal_records_is_current_pr'), 'personal_records', ['is_current_pr'], unique=False)
        op.create_index(op.f('ix_personal_records_sport_type'), 'personal_records', ['sport_type'], unique=False)
        op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    
    if 'segment_efforts' not in existing_tables:
        op.create_table('segment_efforts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('activity_id', sa.Integer(), nullable=True),
            sa.Column('segment_id', sa.Integer(), nullable=False),
            sa.Column('strava_effort_id', sa.String(), nullable=False),
            sa.Column('start_date', sa.DateTime(), nullable=False),
            sa.Column('elapsed_time_seconds', sa.Integer(), nullable=False),
            sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
            sa.Column('average_heartrate', sa.Float(), nullable=True),
            sa.Column('max_heartrate', sa.Float(), nullable=True),
            sa.Column('average_watts', sa.Float(), nullable=True),
            sa.Column('average_cadence', sa.Float(), nullable=True),
            sa.Column('pr_rank', sa.Integer(), nullable=True),
            sa.Column('kom_rank', sa.Integer(), nullable=True),
            sa.Column('is_pr', sa.Boolean(), nullable=True),
            sa.Column('device_watts', sa.Boolean(), nullable=True),
            sa.Column('raw_data', sa.JSON(), nullable=True),
            sa.Column('synced_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
            sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_segment_efforts_activity_id'), 'segment_efforts', ['activity_id'], unique=False)
        op.create_index(op.f('ix_segment_efforts_is_pr'), 'segment_efforts', ['is_pr'], unique=False)
        op.create_index(op.f('ix_segment_efforts_segment_id'), 'segment_efforts', ['segment_id'], unique=False)
        op.create_index(op.f('ix_segment_efforts_start_date'), 'segment_efforts', ['start_date'], unique=False)
        op.create_index(op.f('ix_segment_efforts_strava_effort_id'), 'segment_efforts', ['strava_effort_id'], unique=True)
        op.create_index(op.f('ix_segment_efforts_user_id'), 'segment_efforts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_efforts_user_id'), table_name='segment_efforts')
    op.drop_index(op.f('ix_segment_efforts_strava_effort_id'), table_name='segment_efforts')
    op.drop_index(op.f('ix_segment_efforts_start_date'), table_name='segment_efforts')
    op.drop_index(op.f('ix_segment_efforts_segment_id'), table_name='segment_efforts')
    op.drop_index(op.f('ix_segment_efforts_is_pr'), table_name='segment_efforts')
    op.drop_index(op.f('ix_segment_efforts_activity_id'), table_name='segment_efforts')
    op.drop_table('segment_efforts')
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_sport_type'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_is_current_pr'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_distance_category'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_activity_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_achieved_date'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_injury_risks_user_id'), table_name='injury_risks')
    op.drop_index(op.f('ix_injury_risks_detected_date'), table_name='injury_risks')
    op.drop_table('injury_risks')
    op.drop_index(op.f('ix_segments_strava_segment_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_table('app_state')
    # ### end Alembic commands ###


